# Generated by Django 5.2 on 2025-05-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='nb_inscrit',
        ),
    ]
